### ISSUE TITLE
check_uptime wrong perlre

### ISSUE THREAD

**Issue by sebastien-prudhomme** [willixix/naglio-plugins#11]
elsif ($uptime_output =~ /up\s+(d+)s+days?,s+(d+)s+min/) {

should be

elsif ($uptime_output =~ /up\s+(\d+)\s+days?,\s+(\d+)\s+min/) {

to match :  11:39:53 up 204 days, 21 min,  1 user,  load average: 0.15, 0.15, 0.10

**Comment by willixix** [comment]
Corrected. Thank you for noticing and reporting this.
