### ISSUE TITLE
Problem with the maxmemory calculation in check_redis.pl

### ISSUE THREAD

**Issue by matt448** [willixix/naglio-plugins#12]
First off thanks for this great plugin. Almost wrote my own and this saved me a bunch of time. The issue I think I found has to do with maxmemory when using the mem_utilization option.  I tested using K and M values for the -M maxmemory option and when I run the script it throws this error:

Argument "4000M" isn't numeric in multiplication (*) at ./check_redis.pl line 2550.

I looked at the code and it appears the section that converts K,M,G values to bytes is doing the math operation with the K,M or G still part of the number. 

My quick hack to fix it was to change:

```
elsif ($o_totalmemory =~ /^(\d+K)/) {
       $o_totalmemory = $1*1024;
    }
```

To this:

```
elsif ($o_totalmemory =~ /^(\d+K)/) {
       $o_totalmemory = $1;
       $o_totalmemory =~ s/K//;
       $o_totalmemory = $o_totalmemory*1024;
    }
```

**Comment by willixix** [comment]
Thank you for reporting this issue. The correct fix is to remove K and M out of () in original regex and new version I just committed should have that. Try it and I'll close this issue after.

**Comment by matt448** [comment]
Yep that fixed it. Thanks!
