### ISSUE TITLE
check_snmp_raid.pl: debug mode doesn't work properly

### ISSUE THREAD

**Issue by giner** [willixix/naglio-plugins#20]
"--debug" without an argument doesn't work at all
"--debug=filename" write some information to the file and some other information to the console

**Comment by willixix** [comment]
Should all be fixed now.

Debug used to be enabled with "$DEBUG=1" global variable declared at the top of code with 'printf ... if $DEBUG' lines used for output of debug info. Somewhere around 2 years I added verb() function and proper --debug option from my other plugins but transition was never finished although I intended for 2.1 version to use only that. Now that you reminded me, I looked through it and replaced all old printf with verb() so it should all be right.
