### ISSUE TITLE
Potential stats-parsing issue in check_redis.pl

### ISSUE THREAD

**Issue by mspiegle** [willixix/naglio-plugins#4]
It looks like the parsing of stats key/values goes off-by-1 at some point.  Not sure if this is due to Redis 2.6, but I see the following error when running the script:
Use of uninitialized value in concatenation (.) or string at ./check_redis.pl line 1661.

When the parser gets off-by-1, the line run_id:db543ce9fac79f455eee32d605e1b78dc5e0f93b is interpreted so that the hash string (which starts with db) is interpreted as a key, which matches the '$vnam =~ /^db/' check, and I eventually get an error when it tries to parse/use the expected db status lines.

I was using the latest check_redis.pl from git at the time of this bug report.

<pre>
$ ./check_redis.pl -v -H **** -p ****
check_redis.pl plugin version 0.61
Alarm at 15
connecting to ****:****
[SEND] PING $VAR1 = [];
[SEND RAW] *1
$4
PING
[RECV RAW] '+PONG' at /usr/lib/perl5/site_perl/5.8.8/Redis.pm line 522, <GEN1> chunk 1.
[RECV] PING $VAR1 = 'PONG';
$VAR2 = undef;
[SEND] INFO $VAR1 = [];
[SEND RAW] *1
$4
INFO
[RECV RAW] '$1471' at /usr/lib/perl5/site_perl/5.8.8/Redis.pm line 522, <GEN1> chunk 2.
[RECV RAW] '# Server
redis_version:2.5.9
redis_git_sha1:5ab7eaf8
redis_git_dirty:1
os:Linux 2.6.32-220.7.1.el6.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.6
process_id:2416
run_id:db543ce9fac79f455eee32d605e1b78dc5e0f93b
tcp_port:****
uptime_in_seconds:860179
uptime_in_days:9
lru_clock:237328

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:410064
used_memory_human:400.45K
used_memory_rss:7557120
used_memory_peak:410288
used_memory_peak_human:400.67K
used_memory_lua:30720
mem_fragmentation_ratio:18.43
mem_allocator:jemalloc-2.2.5

# Persistence
loading:0
aof_enabled:1
changes_since_last_save:0
bgsave_in_progress:0
last_save_time:1343690790
last_bgsave_status:ok
bgrewriteaof_in_progress:0
bgrewriteaof_scheduled:0
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:1473
total_commands_processed:1484
instantaneous_ops_per_sec:0
rejected_connections:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:1676

# Replication
role:master
connected_slaves:2
slave0:10.56.124.27,33599,online
slave1:10.144.34.31,47142,online

# CPU
used_cpu_sys:0.89
used_cpu_user:0.92
used_cpu_sys_children:0.01
used_cpu_user_children:0.00

# Keyspace
' at /usr/lib/perl5/site_perl/5.8.8/Redis.pm line 545, <GEN1> chunk 2.
[RECV] INFO $VAR1 = '# Server
redis_version:2.5.9
redis_git_sha1:5ab7eaf8
redis_git_dirty:1
os:Linux 2.6.32-220.7.1.el6.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.6
process_id:2416
run_id:db543ce9fac79f455eee32d605e1b78dc5e0f93b
tcp_port:****
uptime_in_seconds:860179
uptime_in_days:9
lru_clock:237328

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:410064
used_memory_human:400.45K
used_memory_rss:7557120
used_memory_peak:410288
used_memory_peak_human:400.67K
used_memory_lua:30720
mem_fragmentation_ratio:18.43
mem_allocator:jemalloc-2.2.5

# Persistence
loading:0
aof_enabled:1
changes_since_last_save:0
bgsave_in_progress:0
last_save_time:1343690790
last_bgsave_status:ok
bgrewriteaof_in_progress:0
bgrewriteaof_scheduled:0
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:1473
total_commands_processed:1484
instantaneous_ops_per_sec:0
rejected_connections:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:1676

# Replication
role:master
connected_slaves:2
slave0:10.56.124.27,33599,online
slave1:10.144.34.31,47142,online

# CPU
used_cpu_sys:0.89
used_cpu_user:0.92
used_cpu_sys_children:0.01
used_cpu_user_children:0.00

# Keyspace
';
$VAR2 = undef;
[SEND] QUIT $VAR1 = [];
[SEND RAW] *1
$4
QUIT
Stats Line: last_save_time = 1343690790
Stats Line: bgsave_in_progress = 0
Stats Line: 1676 = # Replication
Stats Line: 2.5.9 = redis_git_sha1
Stats Line: 860179 = uptime_in_days
Stats Line: db543ce9fac79f455eee32d605e1b78dc5e0f93b = tcp_port
Use of uninitialized value in concatenation (.) or string at ./check_redis.pl line 1661.
 - stats data added: db543ce9fac79f455eee32d605e1b78dc5e0f93b_tcp_port = 
Stats Line: 1 = os
Stats Line: 4.4.6 = process_id
Stats Line: loading = 0
Stats Line: **** = uptime_in_seconds
Stats Line: aof_pending_bio_fsync = 0
Stats Line: 0.92 = used_cpu_sys_children
Stats Line: # Stats = total_connections_received
Stats Line: connected_clients = 1
Stats Line: 2416 = run_id
Stats Line: client_biggest_input_buf = 0
Stats Line: changes_since_last_save = 0
Stats Line: Linux 2.6.32-220.7.1.el6.x86_64 x86_64 = arch_bits
Stats Line: 410288 = used_memory_peak_human
Stats Line: role = master
Stats Line: aof_pending_rewrite = 0
Stats Line: bgrewriteaof_scheduled = 0
Stats Line: 237328 = # Clients
Stats Line: 7557120 = used_memory_peak
Stats Line: jemalloc-2.2.5 = # Persistence
Stats Line: aof_buffer_length = 0
Stats Line: # Memory = used_memory
Stats Line: aof_delayed_fsync = 0
Stats Line: slave0 = 10.56.124.27,33599,online
Stats Line: 5ab7eaf8 = redis_git_dirty
Stats Line: aof_base_size = 0
Stats Line: 18.43 = mem_allocator
Stats Line: 0.01 = used_cpu_user_children
Stats Line: 0 = latest_fork_usec
Stats Line: # Server = redis_version
Stats Line: 0.89 = used_cpu_user
Stats Line: aof_current_size = 0
Stats Line: 30720 = mem_fragmentation_ratio
Stats Line: epoll = gcc_version
Stats Line: client_longest_output_list = 0
Stats Line: 64 = multiplexing_api
Stats Line: blocked_clients = 0
Stats Line: 400.67K = used_memory_lua
Stats Line: aof_enabled = 1
Stats Line: 9 = lru_clock
Stats Line: # CPU = used_cpu_sys
Stats Line: 1473 = total_commands_processed
Stats Line: 400.45K = used_memory_rss
Stats Line: bgrewriteaof_in_progress = 0
Stats Line: slave1 = 10.144.34.31,47142,online
Stats Line: 1484 = instantaneous_ops_per_sec
Stats Line: 0.00 = # Keyspace
Stats Line: connected_slaves = 2
Stats Line: last_bgsave_status = ok
Stats Line: 410064 = used_memory_human
Calculated Data: total_keys=0
Calculated Data: total_expires=0
OK: REDIS  on ****:**** has 1 databases (db543ce9fac79f455eee32d605e1b78dc5e0f93b)
</pre>

**Comment by willixix** [comment]
There are two issues here:

1) Library was not able to properly parse response that contained #comments. That is what caused off by 1 as you can see from above output. The plugin just parses each line and these were wrong.
2) There was a value that started with db but was not expected db info. This was supposed to be just a random hex value, and its pretty rare for it to start with db but possible. This is where you see initialization value error (in a verb function used for debug output). I'll update plugin to better deal with such a case. 

But main issue here is redis perl library and probably related to 2.6 beta redis version. You'll have to contact library developer to fix it or do it yourself and send a patch.

**Comment by mspiegle** [comment]
Thanks for the quick response.  I've silenced warnings on my system for now since I don't actually need the key/value info yet.  There seems to be other clients which are barfing on 2.6's new format as well - credis is one of them.

I have over 600 redis instances running in my environment, so I randomly ended up with a few of those 'db' hashes which caused the problem.

Regards,
Mike

**Comment by mspiegle** [comment]
FWIW, I changed the /^db/ regex to read: /^db\d+$/ and it seems to be working-around the Redis.pm issue.

**Comment by willixix** [comment]
I changed it to the regex you suggested a month ago. And core of the problem here is the perl redis library and not the plugin. Before I close this issue, can I get your name for contributors section. Thanks.
