### ISSUE TITLE
Mysql nagios plugin shows error

### ISSUE THREAD

**Issue by yashgt** [willixix/naglio-plugins#6]
My pnp4nagios version is pnp4nagiosâ0.6.18

The Redis and Memcached plugins work beautifully and show the graphs in Nagios. The MySQL plugin shows the following error.

Please check the documentation for information about the following error.

XML file "/usr/local/pnp4nagios/var/perfdata/localhost/MYSQLD.xml" not found. Read FAQ online
file [line]:

application/models/data.php [312]:
 I see the following files in perfdata:
root@v-enterprise15:/usr/local/pnp4nagios# ls -f var/perfdata/localhost/*
var/perfdata/localhost/Current_Load.rrd var/perfdata/localhost/MYSQLD_open_tables.rrd var/perfdata/localhost/Root_Partition.rrd
 var/perfdata/localhost/Current_Load.xml var/perfdata/localhost/MYSQLD_questions.rrd var/perfdata/localhost/Root_Partition.xml
var/perfdata/localhost/Current_Users.rrd var/perfdata/localhost/MYSQLD_slow_queries.rrd var/perfdata/localhost/SOLR.rrd
 var/perfdata/localhost/Current_Users.xml var/perfdata/localhost/MYSQLD_threads_connected.rrd var/perfdata/localhost/SOLR.xml
var/perfdata/localhost/Memcached.rrd var/perfdata/localhost/MYSQLD_uptime.rrd var/perfdata/localhost/Swap_Usage.rrd
 var/perfdata/localhost/Memcached.xml var/perfdata/localhost/Redis.rrd var/perfdata/localhost/Swap_Usage.xml
var/perfdata/localhost/MYSQLD_connection_time.rrd var/perfdata/localhost/Redis.xml

What might be the problem. Any help would be appreciated.

**Comment by willixix** [comment]
This is not an error with a plugin. It is an error with your configuration - nagios or pnp. The only thing I can tell from above is that data from plugin was not processed by pnp. To see what the problem is you'd have to check pnp4nagios logs, possibly enabling debug mode. Like the error said, you need to read FAQ.
