### ISSUE TITLE
check_snmp_netint: administrative down should be ignored when checking operational up

### ISSUE THREAD

**Issue by liedekef** [willixix/naglio-plugins#7]
Please add an option to ignore interfaces that are administrative DOWN when checking for operational UP interfaces.
This happens all the time: a server has many interfaces but a number of them might not be configured and thus be down.
I made this change for the original plugin, so if you want I can send you the diff.

**Comment by willixix** [comment]
Yes, send this in. But this diff should be against check_netint.pl as there will not be any more updates to check_snmp_netint.

**Comment by liedekef** [comment]
Ok, I'll try. But I saw that the code of check_netint.pl still contains some references to check_snmp_netint (in the comments).

**Comment by willixix** [comment]
It is still the same base code with new additions, so plenty of references to check_snmp_netint :)

**Comment by liedekef** [comment]
Ok, diff done (some typos fixed as well, and a small change so the '-z' option no longer creates temporary files anymore. But since I can't upload diffs: where or how can I send them to you?

**Comment by willixix** [comment]
the diff is committed into main branch for check_netint

**Comment by willixix** [comment]
thank you
